### ISSUE TITLE
Pro-flashlight loses it's weight when teleporting

### ISSUE THREAD

**Issue by 0RadicalLarry0** [SirTyler/BetterTeleporter#11]
As title says, when using a teleporter with a pro-flashlight it won't weigh 5 pounds anymore. Dropping the flashlight and picking it up still results in it being weightless.

It can be fixed by teleporting without it in your inventory and then picking it up again.

**Comment by 0RadicalLarry0** [comment]
I only tested this with a normal teleporter not inverse in case that somehow makes any difference.

**Comment by SirTyler** [comment]
Should be fixed in Update 1.2.2
