### ISSUE TITLE
Items being dropped when using the regular teleporter

### ISSUE THREAD

**Issue by JustCallMeQuincy** [SirTyler/BetterTeleporter#3]
Hi there! I found your plugin and it looks very promising.

Sadly - after some testing - I've found that teleporting people would still drop their items.

I've tried resetting the config (removing and regenerating), using older versions, not using any other mods and teleporting others instead of myself.
All of these tests had the same result of the Walkie-Talkie being dropped upon being teleported, basically the vanilla mechanic.

I haven't tested the inverse teleporter but I mainly use the regular one and I was hoping for some help to resolve this issue.

Below you will find my config file (just in case).

Thanks a lot!

[BetterTeleporter.zip](https://github.com/SirTyler/BetterTeleporter/files/13679541/BetterTeleporter.zip)

**Comment by SirTyler** [comment]
Version 1.1.0 and 1.1.1 does not support regular teleporters just yet, as is stated in the patch notes. Version 1.2.0 is ready for release just needs some more testing before it goes out and **WILL** support both regular and inverse teleportation.

**Comment by JustCallMeQuincy** [comment]
Ok awesome! Thanks a lot :D

Very excited for that update!
