### ISSUE TITLE
KeepItemList doesn't seem to work for regular teleporter?

### ISSUE THREAD

**Issue by MasterEvilAce** [SirTyler/BetterTeleporter#5]
While the Inverse teleporter works fine.

Using 1.1.1 and the same config for both.
KeepItemList = KeyItem,FlashlightItem,WalkieTalkie

Regular teleporter drops everything everytime. We all used the same mods with the same configuration.

**Comment by SirTyler** [comment]
Same as this issue: #3 

> Version 1.1.0 and 1.1.1 does not support regular teleporters just yet, as is stated in the patch notes. Version 1.2.0 is ready for release just needs some more testing before it goes out and WILL support both regular and inverse teleportation.
