### ISSUE TITLE
A way to add Shovels to come with?

### ISSUE THREAD

**Issue by TakAttak** [SirTyler/BetterTeleporter#9]
Not so much an issue as a question. I tried to follow the same naming conventions for the flashlight and key, but the Shovel didn't come through. Was wondering if there was something I was missing when adding it to the configuration.

**Comment by SirTyler** [comment]
So the config file works off the item names in the game code, so it isn't always super consistent. I might go and make a full list of the items sometime this week but for shovels it should be: "Shovel" and not "ShovelItem"

**Comment by TakAttak** [comment]
That would be where I messed up then, thank you! Now we can go in with a false sense of protection as I swing and die to everything inside.
